<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Interfaces\DataBase\" />
    <Folder Include="Interfaces\External\" />
    <Folder Include="UseCases\Pedidos\Commands\DeletePedido\" />
    <Folder Include="UseCases\Pedidos\Commands\UpdatePedido\" />
    <Folder Include="UseCases\Pedidos\Queries\GetAllPedido\" />
    <Folder Include="UseCases\Pedidos\Queries\GetByIdPedido\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

</Project>
